name: pretty_json_mixin
description: A mixin overrides the toString() method to return a pretty JSON string.
version: 0.1.0
homepage: https://github.com/jezsung/pretty_json_mixin

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
